name: Use Github Actions Secret

on:
  workflow_dispatch:

jobs:
  say_secret:
    runs-on: ubuntu-latest
    steps:
      - run: echo "the secret value is ${{ secrets.A_SECRET_VALUE }}!"
      - run: 'echo "SESSION_SECRET: hogehoge" > file'
      - run: cat file
      - run: sed -i -e 's/SESSION_SECRET: .*$/SESSION_SECRET: ${{ secrets.A_SECRET_VALUE }}/' file
      - run: cat file
